### ISSUE TITLE
Fails in .net 5

### ISSUE THREAD

**Issue by BlackWolves-nl** [Currence-Online/emandates-libraries-dotnet-core#2]
The check signature in xmlprocessor fails when referencing the package System.Security.Cryptography.Xml (5.0.0) in your project.
Failing on line  160 in xmlProcessor:
if (!signedXml.CheckSignature(incomingCertificate, true))

Exception:
System.NullReferenceException
  Message=Object reference not set to an instance of an object.
  Source=System.Security.Cryptography.Xml
  StackTrace:
   at System.Security.Cryptography.Xml.SignedXml.IsKeyTheCorrectAlgorithm(AsymmetricAlgorithm key, Type expectedType)
   at System.Security.Cryptography.Xml.SignedXml.CheckSignedInfo(AsymmetricAlgorithm key)
   at System.Security.Cryptography.Xml.SignedXml.CheckSignature(AsymmetricAlgorithm key)
   at System.Security.Cryptography.Xml.SignedXml.CheckSignature(X509Certificate2 certificate, Boolean verifySignatureOnly)
   at eMandates.Merchant.Library.XML.XmlProcessor.CheckIdxSignature(XmlDocument document, XmlElement signature) in C:\Users\Niels\Desktop\emandates-libraries-dotnet-core-master\DotNet\eMandates.Merchant.Library\XML\XmlProcessor.cs:line 160

Any ideas how to fix this?

**Comment by BlackWolves-nl** [comment]
Looks like changing this
if (!signedXml.CheckSignature(incomingCertificate, true))
to this
if(!XmlSignature.CheckSignature(document, incomingCertificate, signature))
fixes it. Not sure if that is the right way but it works for now.
